services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_sig_app
    volumes:
      - ..:/workspace:cached
      - nestjs_sig_node_modules:/workspace/sistema-integrado-gestao-backend/node_modules
    command: |
      bash -c "
        mkdir -p /workspace/sistema-integrado-gestao-backend/node_modules &&
        sleep infinity
      "
    environment:
      - DATABASE_URL=mysql://nestjs_sig:nestjs_sig_pass@db:3306/nestjs_sig
      - NODE_ENV=development
    ports:
      - "3000:3000"
    networks:
      - nestjs_sig_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: nestjs_sig_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjs_sig
      MYSQL_USER: nestjs_sig
      MYSQL_PASSWORD: nestjs_sig_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nestjs_sig_network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.7
    restart: always
    command: ["start-dev"]
    volumes:
      - ./keycloak/data/import:/opt/keycloak/data/import
    environment:
      - KC_DB=mysql
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak_password
      - KC_DB_URL_HOST=db
      - KC_DB_URL_PORT=3306
      - KC_DB_SCHEMA=keycloak
      - KC_FEATURES=scripts
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=9080
    ports:
      - "9080:9080"
    depends_on:
      - db
    networks:
      - nestjs_sig_network

networks:
  nestjs_sig_network:
    name: nestjs_sig_network_dev

volumes:
  mysql-data:
    name: nestjs_sig_mysql_data_dev
  nestjs_sig_node_modules:
    name: nestjs_sig_node_modules_dev
